- README.md
- proxies/live/apiproxy/policies/Javascript.AddClientRPDetailsHeader.xml
- proxies/live/apiproxy/resources/jsc/ClientRPDetailsHeader.SetRequestHeaders.js
- proxies/live/apiproxy/targets/target.xml
> [NRLF-192] Add NHSD-Client-RP-Details header

- README.md
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- tests/api_tests.py
> [NRLF-120] Enable status endpoint

- README.md
- manifest_template.yml
- proxies/sandbox/apiproxy/policies/FlowCallout.ApplyRateLimiting.xml
- proxies/sandbox/apiproxy/policies/Javascript.AddClientRPDetailsHeader.xml
- proxies/sandbox/apiproxy/policies/Javascript.AddConnectionMetadataHeader.xml
- proxies/sandbox/apiproxy/policies/javascript.WritePathToVariable.xml
- proxies/sandbox/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/targets/sandbox.xml
> [NRLF-187] Enable sandbox (internal-dev-sandbox)

- Makefile
- README.md
- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
- proxies/sandbox/apiproxy/resources/jsc/ClientRPDetailsHeader.SetRequestHeaders.js
- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
- proxies/sandbox/apiproxy/resources/jsc/WritePathToVariable.js
- pytest.ini
- tests/common_tests.py
- tests/sandbox_smoke_tests.py
- tests/smoke_tests.py
> [NRLF-187] deploy to sandbox env

- azure/azure-release-pipeline.yml
> [NRLF-119] Patch release pipeline

- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [NRLF-276] update sandbox org pointer types

- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [NRLF-276] updated nrlPointers for sandbox

- package.json
- poetry.lock
> NRLF-260-dependabot-updates first stab at dependabot fixes

- Makefile
- proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
- proxies/live/apiproxy/resources/jsc/WritePathToVariable.js
- proxies/live/apiproxy/targets/target.xml
- proxies/sandbox/apiproxy/resources/jsc/WritePathToVariable.js
- proxies/sandbox/apiproxy/targets/sandbox.xml
> [NRLF-253] Use Domain Names

- azure/azure-release-pipeline.yml
- manifest_template.yml
> [NRLF-274] Enable INT APIGEE Proxy

- azure/azure-release-pipeline.yml
- manifest_template.yml
> [NRLF-253] Enable all Non-Prod environments

- azure/azure-release-pipeline.yml
> [NRLF-273] Added prod to azure-release-pipeline.yml

- azure/azure-release-pipeline.yml
> [NRLF-273] Removed smoke tests for prod in azure-release-pipeline.yml

- manifest_template.yml
> [NRLF-273] Added ratelimit and quota to prod environment

- Makefile
- azure/templates/run-smoke-tests.yml
- tests/configuration/config.py
- tests/sandbox_smoke_tests.py
- tests/smoke_tests.py
> [NRLF-273] Corrected () to {} in Makefile smoketest and added check for APIGEE_APP_ID before running a prod smoketest

- Makefile
> [NRLF-273] Remove proxy-name and api-name args for int and prod in Makefile

- Makefile
> [NRLF-273] Added -k arg to only run status endpoint test in prod envs

- specification/nrl-producer-api.yaml
> [NRLF-348] Reduce OAS Complexity

- tests/sandbox_smoke_tests.py
- tests/smoke_tests.py
> [NRLF-362] Disabled inconsistent tests

- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
- specification/nrl-producer-api.yaml
> [NRLF-372] OAS iteration

- specification/nrl-producer-api.yaml
> [NRLF-372] OAS Iterations

- proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddSandboxAuthorization.xml
- proxies/sandbox/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/targets/sandbox.xml
- specification/nrl-producer-api.yaml
Amendments to CORS for all proxies and Authentication for Sandbox.
> [NRLF-186] Try our API compatibility

- azure/azure-release-pipeline.yml
> [NRLF-374] Added prod_requires_approval flag in azure-pipelines-release.yml

- azure/azure-release-pipeline.yml
> [NRLF-374] depends_on changes for prod

- proxies/live/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/proxies/default.xml
- specification/nrl-producer-api.yaml
> Release 2023-03-14

- tests/smoke_tests.py
> [NRLF-387] Disable Smoke Tests

- manifest_template.yml
> [NRLF-422] configure rate limiting

- proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [NRLF-284] Change separator to whitespace for nrlPointerTypes

- specification/nrl-producer-api.yaml
> [NRLF-414] Updated nrl-producer-api.yml

- specification/nrl-producer-api.yaml
> [NRLF-414] updated nrl-producer-api.yaml

- specification/nrl-producer-api.yaml
> [NRLF-396] Removed custodian from producer search endpoints

- README.md
- azure/project.yml
- package.json
- postman/national_record_locator_producer_sandbox.json
- specification/record-locator/producer.yaml
> [NRLF-399] update apigee paths

- specification/record-locator/producer.yaml
> Release 2023-04-06

- specification/record-locator/producer.yaml
> [NRLF-461] onboarding text

- specification/record-locator/producer.yaml
> [NRLF-437] tweak description of x-ids

- proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
- specification/record-locator/producer.yaml
> [NRLF-425] Added NHSD-End-User-Organisation header info

- specification/record-locator/producer.yaml
> [NRLF-425] [NRLF-470] [NRLF-461] include relatesTo, swagger regen for NRLF-425 & re-implement NRLF-461

- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [NRLF-479] Revert the splitting of nrl pointers in sandbox

- specification/record-locator/producer.yaml
> [NRLF-470] Added missing immutable fields to narrative

- specification/record-locator/producer.yaml
> [NRLF-425] odsCodeExtension on swagger not showing resolved

- specification/record-locator/producer.yaml
> [NRLF-425] Renamed RequestHeaderReceiverCode to RequestHeaderOrganisationExtensionCode

- specification/record-locator/producer.yaml
> [NRLF-425] Added missing ods code extension for endpoints

- specification/record-locator/producer.yaml
> [NRLF-425] Fix typo in header param

- proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [NRLF-395] Added logic to append NHSD-One-Directional-Sync header

- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [NRLF-549] audit-permissions removed permission from sandbox

- specification/record-locator/producer.yaml
> [NRLF-522] Added Errors section producer.yaml

- specification/record-locator/producer.yaml
> [NRLF-522] Bullet points on errors

- proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [Feature NRLF-593]  Custom Attribute toggle for S3 Auth

- specification/record-locator/producer.yaml
> made changes to reflect NRL-494

- specification/record-locator/producer.yaml
> [NRLF-559] author-immutable added author to immutable fields

- specification/record-locator/producer.yaml
> [NRLF-640] Update producer.yaml

- specification/record-locator/producer.yaml
> [NRLF-585] live urls to narrative

- specification/record-locator/producer.yaml
> [NRLF-680] Revert NRLF-494 regex changes

- package-lock.json
- package.json
> [NRLF-583] Remove Newman

- specification/record-locator/producer.yaml
> [NRLF-663] Add Open Source Narrative

- specification/record-locator/producer.yaml
> [SPINECLI-1190] Add link to postman collection in narrative

- pyproject.toml
> [SPINECLI-1795] Fix azure pipelines requires pyproject

- specification/record-locator/producer.yaml
Sync documentation updates from NRLF
> SPINECLI-1666 producer documentation updates from NRLF

- specification/record-locator/producer.yaml
> NRL-496 - update yaml

- proxies/sandbox/apiproxy/policies/RaiseFault.400MissingODSHeader.xml
> [NRL-602] Fix typo in sandbox 400 error

- specification/record-locator/producer.yaml
> [NRL-670] Add ASID to context.related in spec examples 

- azure/azure-release-pipeline.yml
- manifest_template.yml
> [NRL-540] Add deployment for ref apigee proxy to release pipeline

- specification/record-locator/producer.yaml
> NRL-702 update documentation for category

- manifest_template.yml
> [NRL-540] Add ratelimiting to ref to match prod

- proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> NRL-759 add new id for nrl permissions

- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> [NRL-855] Add app-id to sandbox proxy headers

- specification/record-locator/producer.yaml
> NRL-820 Add new pointer types to docs

- specification/record-locator/producer.yaml
> [NRL-1007] Make X-Request-Id a required header in the API spec

- specification/record-locator/producer.yaml
> NRL-1028 Update service level in spec to gold

- proxies/live/apiproxy/policies/RaiseFault.403MissingNRLAppID.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
- proxies/live/apiproxy/targets/target.xml
> NRL-818 raise fault for missing nrl app id attribute

- proxies/live/apiproxy/policies/RaiseFault.403MissingNRLAppID.xml
> switch quotes

- specification/record-locator/producer.yaml
> NRL-476 update spec

- specification/record-locator/producer.yaml
> NRL-474 update author documentation

- specification/record-locator/producer.yaml
> update docs to have category in description

- specification/record-locator/producer.yaml
> NRL478 update docs for context

- specification/record-locator/producer.yaml
> [NRL-518] Validate content

- specification/record-locator/producer.yaml
> [NRL-1228] Fix advance care plan naming

- proxies/live/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/targets/sandbox.xml
> [NRL-1322] Set condition to check headers when using AddCors step

- .github/workflows/continuous-integration.yml
> [NRL-1322] Fix release pipeline issue

- proxies/sandbox/apiproxy/proxies/default.xml
> [NRL-1322] Fix sandbox proxy to work with browser CORS

- Makefile
- README.md
- proxies/live/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/live/apiproxy/policies/AssignMessage.AddCorsPreflight.xml
- proxies/live/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
- proxies/sandbox/apiproxy/policies/AssignMessage.AddCorsPreflight.xml
- proxies/sandbox/apiproxy/proxies/default.xml
> NRL-1330 fix cors issue

- specification/record-locator/producer.yaml
> NRL-523 remove 404 from delete docs

- specification/record-locator/producer.yaml
> NRL-505 Modify error documentation

- specification/record-locator/producer.yaml
* Routine Change to reflect all current pointer types and categories in public docs
* NRL-1472 in NRLF introduces the `Appointment `type and the associated category, `Record artifact`
> NRL-1472 add Appointment values

- package-lock.json
- proxies/live/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
- proxies/sandbox/apiproxy/resources/jsc/ConnectionMetadata.SetRequestHeaders.js
> remove ods extension header

- .github/workflows/continuous-integration.yml
> NRL-1544 Automatic build of documentation

- .github/CODEOWNERS
> [NRL-1585] Add CODEOWNERS

- specification/record-locator/producer.yaml
Added the controller catalogue section to the page, including raw link to the catalogue
Updated document with a Controller Catalogue section, including the new link
> NRL-1541 add controller catalogue

- specification/record-locator/producer.yaml
> NRL-1554 Add content retrieval mechanism to documentation

- specification/record-locator/producer.yaml
> NRL-1491 in-context retrieval mechanism

- specification/record-locator/producer.yaml
* Routine docs change to reflect added functionality and use cases
> NRL-1667 update guidance for MIME types and fix formatting
